# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#removed existing package-lock.json files and node_modules file
name: NPM and Python processes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up NPM v 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
      env:
        CI: false
        working-directory: ~/Pomodory/frontend/pomodory-web
    - run: cd ./frontend/pomodory-web && npm install 
    - run: cd ./frontend/pomodory-web && npm run build
    - run: pwd
    - run: ls
 
    
  
    - uses: actions/checkout@v3
    - name: Set up Python 3.7.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.7.16"
      env:
        working-directory: ~/Pomodory/backend
    - name: Install dependencies
      run: 
        python3 -m pip install --upgrade pip
        if [ -f ~/requirements.txt ]; then pip install -r ~/requirements.txt; fi
    
    - name: Copy Build files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ec2-54-237-22-243.compute-1.amazonaws.com
        username: ec2-user
        port: 22
        key: ${{ secrets.KEY }}
        source: "~/Pomodory/frontend/pomodory-web/build"
        target: "~/Pomodory/frontend/pomodory-web"
        
        
    - name: Run commands to run backend and frontend on EC2 instance
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ec2-54-237-22-243.compute-1.amazonaws.com
        username: ec2-user
        key: ${{ secrets.KEY }}
        port: 22
        
        script: 
          killall python3
          killall node
          nohup python3 ~/Pomodory/backend/main.py > ~/Pomodory/backend/nohup.out &
          nohup npx serve ~/Pomodory/frontend/pomodory-web/build &> ~/Pomodory/frontend/pomodory-web/nohup.out &
